import { StyleSheet, Dimensions } from "react-native";

const { width, height } = Dimensions.get("window");
const COLORS = {
  primary: "#0979B0",
  accent: "#3498db",
  background: "#f0f4f8",
  white: "#fff",
  text: "#222",
  textLight: "#444",
  border: "#e0e0e0",
  error: "#e74c3c",
  success: "#2ecc71",
  disabled: "#888",
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
    position: "relative",
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: COLORS.background,
  },
  loadingText: {
    marginTop: 16,
    fontSize: 18,
    color: COLORS.primary,
    fontWeight: "bold",
  },
  marker: {
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: COLORS.white,
    borderRadius: 20,
    padding: 4,
    shadowColor: COLORS.text,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 4,
    elevation: 3,
  },
  infoContainer: {
    backgroundColor: COLORS.white,
    borderRadius: 10,
    padding: 12,
    width: width * 0.92,
    maxWidth: 420,
    shadowColor: COLORS.text,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
    marginBottom: 8,
  },
  infoRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 6,
  },
  infoText: {
    fontSize: 16,
    color: COLORS.text,
    marginLeft: 8,
    fontWeight: "500",
  },
  coordsText: {
    fontSize: 14,
    color: COLORS.textLight,
    marginRight: 12,
  },
  userSelector: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: COLORS.primary,
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 22,
    position: "absolute",
    bottom: 16,
    left: width * 0.04,
    right: width * 0.04,
    elevation: 4,
    shadowColor: COLORS.text,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.10,
    shadowRadius: 4,
  },
  userSelectorText: {
    color: COLORS.white,
    fontSize: 16,
    fontWeight: "bold",
    marginLeft: 8,
  },
  noLocation: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: COLORS.background,
  },
  noLocationText: {
    marginTop: 12,
    fontSize: 18,
    color: COLORS.disabled,
    fontWeight: "500",
  },
  noDevicesCentered: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: COLORS.background,
  },
  noDevicesText: {
    marginTop: 12,
    fontSize: 18,
    color: COLORS.disabled,
    fontWeight: "500",
  },
});

export default styles;
